### ISSUE TITLE
LMS: Documentation Required 

### ISSUE THREAD

**Issue by jainppallav** [RRZE-HPC/LMS#1]
Please provide documentation for installation/setup. As I am newbie to this field, hence it's difficult to understand the whole process like what and where to put on compute nodes and master node.

**Comment by TomTheBear** [comment]
I added an extra INSTALL file. Most information was already in the README/INSTALL files in the subfolders as there is no 'one-command-installs-anything' thing. The LMS should be more a collection of smaller tools to set up a monitoring stack.
